### PR TITLE
Bump to 0.2.0 and update to pronto 0.10

### PR DESCRIPTION
**Pull request by grodowski**

### CODE REVIEW

**Comment by jbarber** [comment]
@grodowski is this PR still relevent?

**Comment by grodowski** [comment]
This PR was required to update `pronto` to `0.10.0` in `circlemator`, but somehow I didn't get to merge it and probably fixed the problem differently, so not a top priority but still relevant.

**Comment by jbarber** [comment]
Ok - you should just merge it after removing the ruby version updates? (I updated the ruby version to 2.7.1)

**Comment by grodowski** [comment]
Closing in favour of dependabot PRs

**Pull request closed without merging**
